# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: baikal/language/dict_common.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='baikal/language/dict_common.proto',
  package='baikal.language',
  syntax='proto3',
  serialized_options=b'Z\037baikal.ai/proto/baikal/language',
  serialized_pb=b'\n!baikal/language/dict_common.proto\x12\x0f\x62\x61ikal.language\"\xa2\x01\n\x07\x44ictSet\x12\x32\n\x05items\x18\x01 \x03(\x0b\x32#.baikal.language.DictSet.ItemsEntry\x12\'\n\x04type\x18\x02 \x01(\x0e\x32\x19.baikal.language.DictType\x12\x0c\n\x04name\x18\n \x01(\t\x1a,\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01*B\n\x08\x44ictType\x12\x0f\n\x0bTOKEN_INDEX\x10\x00\x12\r\n\tWORD_LIST\x10\x01\x12\x16\n\x12WORD_LIST_COMPOUND\x10\x02\x42!Z\x1f\x62\x61ikal.ai/proto/baikal/languageb\x06proto3'
)

_DICTTYPE = _descriptor.EnumDescriptor(
  name='DictType',
  full_name='baikal.language.DictType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TOKEN_INDEX', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORD_LIST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORD_LIST_COMPOUND', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=219,
  serialized_end=285,
)
_sym_db.RegisterEnumDescriptor(_DICTTYPE)

DictType = enum_type_wrapper.EnumTypeWrapper(_DICTTYPE)
TOKEN_INDEX = 0
WORD_LIST = 1
WORD_LIST_COMPOUND = 2



_DICTSET_ITEMSENTRY = _descriptor.Descriptor(
  name='ItemsEntry',
  full_name='baikal.language.DictSet.ItemsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='baikal.language.DictSet.ItemsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='baikal.language.DictSet.ItemsEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=217,
)

_DICTSET = _descriptor.Descriptor(
  name='DictSet',
  full_name='baikal.language.DictSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='baikal.language.DictSet.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='baikal.language.DictSet.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='baikal.language.DictSet.name', index=2,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DICTSET_ITEMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=217,
)

_DICTSET_ITEMSENTRY.containing_type = _DICTSET
_DICTSET.fields_by_name['items'].message_type = _DICTSET_ITEMSENTRY
_DICTSET.fields_by_name['type'].enum_type = _DICTTYPE
DESCRIPTOR.message_types_by_name['DictSet'] = _DICTSET
DESCRIPTOR.enum_types_by_name['DictType'] = _DICTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DictSet = _reflection.GeneratedProtocolMessageType('DictSet', (_message.Message,), {

  'ItemsEntry' : _reflection.GeneratedProtocolMessageType('ItemsEntry', (_message.Message,), {
    'DESCRIPTOR' : _DICTSET_ITEMSENTRY,
    '__module__' : 'baikal.language.dict_common_pb2'
    # @@protoc_insertion_point(class_scope:baikal.language.DictSet.ItemsEntry)
    })
  ,
  'DESCRIPTOR' : _DICTSET,
  '__module__' : 'baikal.language.dict_common_pb2'
  # @@protoc_insertion_point(class_scope:baikal.language.DictSet)
  })
_sym_db.RegisterMessage(DictSet)
_sym_db.RegisterMessage(DictSet.ItemsEntry)


DESCRIPTOR._options = None
_DICTSET_ITEMSENTRY._options = None
# @@protoc_insertion_point(module_scope)
