name: KoNLPy CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ["3.6", "3.7"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: before_install
        run: |
          pip install -r requirements.txt
          pip install coveralls
          pip install pytest-cov

      - name: install
        run: python setup.py -q install

      - name: after_success
        env: 
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: coveralls

      - name: script
        run: |
          coverage run --source=konlpy -m pytest -k 'not (komoran or mecab)'